name: Build and Release
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          workdir: src
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

  # Create release job. Creates a new release when Build job succeeds.
  create-release:
    name: Create Release
    needs: build-android
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "yebekhe@gmail.com"
          git config --global user.name "YeBeKhe"

      - name: Get latest release
        id: latest_release
        uses: peter-evans/get-latest-release@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}

      - name: Extract release version
        id: extract_release_version
        run: echo "::set-output name=version::${{ steps.latest_release.outputs.tag_name }}"

      - name: Extract release count
        id: extract_release_count
        run: |
          releases_count=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases" | jq '. | length')
          echo "::set-output name=count::$(($releases_count + 1))"

      - name: Set release details
        id: set_release_details
        run: |
          release_version="${{ steps.extract_release_version.outputs.version }}"
          release_count="${{ steps.extract_release_count.outputs.count }}"
          new_version="0.2.${{ steps.extract_release_count.outputs.count }}" # increment the version by 1

          echo "::set-output name=tag::v${new_version}-beta.${release_count}"
          echo "::set-output name=name::Beta Release ${new_version}.${release_count}"
          echo "::set-output name=body::Changes in this release:\n- fixed bug"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_release_details.outputs.tag }}
          release_name: ${{ steps.set_release_details.outputs.name }}
          body: ${{ steps.set_release_details.outputs.body }}
          draft: false
          prerelease: true

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: package.zip
          asset_content_type: application/zip
          asset_path: ${{ steps.build-android.outputs.artifact-path }}
